### ISSUE TITLE
Error when building godot with scons

### ISSUE THREAD

**Issue by PixsaOJ** [godot-extended-libraries/tensorflow#1]
Hi, Im trying to follow instructions on main repo.
I get this errors when i try tu build godot with scons

`
scons: *** [modules\tensorflow\tensorflow.windows.tools.64.obj] Error 2
C:\Users\admin\Desktop\godot\thirdparty\tensorflow\tensorflow/lite/c/c_api_internal.h(82): warning C4200: nonstandard extension used: zero-sized array in struct/union
C:\Users\admin\Desktop\godot\thirdparty\tensorflow\tensorflow/lite/c/c_api_internal.h(82): note: This member will be ignored by a defaulted constructor or copy/move ass
ignment operator
C:\Users\admin\Desktop\godot\thirdparty\tensorflow\tensorflow/lite/c/c_api_internal.h(116): warning C4200: nonstandard extension used: zero-sized array in struct/union
C:\Users\admin\Desktop\godot\thirdparty\tensorflow\tensorflow/lite/c/c_api_internal.h(116): note: This member will be ignored by a defaulted constructor or copy/move as
signment operator
scons: building terminated because of errors.
`

**Comment by fire** [comment]
Can you post a longer transcript? The error isn't in your message.

**Comment by PixsaOJ** [comment]
Im sorry i am late, will post longer transcript soon.

**Comment by fire** [comment]
I have made an update to the repo. Another person tested that it works for him.
